#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-HTML-Form
Version  : 6.10
Release  : 16
URL      : https://cpan.metacpan.org/authors/id/S/SI/SIMBABQUE/HTML-Form-6.10.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/S/SI/SIMBABQUE/HTML-Form-6.10.tar.gz
Summary  : 'Class that represents an HTML form element'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-HTML-Form-license = %{version}-%{release}
Requires: perl-HTML-Form-perl = %{version}-%{release}
Requires: perl(HTML::Tagset)
Requires: perl(HTML::TokeParser)
Requires: perl(HTTP::Request)
Requires: perl(HTTP::Request::Common)
Requires: perl(HTTP::Response)
Requires: perl(LWP::MediaTypes)
Requires: perl(URI)
BuildRequires : buildreq-cpan
BuildRequires : perl(HTML::Tagset)
BuildRequires : perl(HTML::TokeParser)
BuildRequires : perl(HTTP::Request)
BuildRequires : perl(HTTP::Request::Common)
BuildRequires : perl(HTTP::Response)
BuildRequires : perl(LWP::MediaTypes)
BuildRequires : perl(URI)

%description
No detailed description available

%package dev
Summary: dev components for the perl-HTML-Form package.
Group: Development
Provides: perl-HTML-Form-devel = %{version}-%{release}
Requires: perl-HTML-Form = %{version}-%{release}

%description dev
dev components for the perl-HTML-Form package.


%package license
Summary: license components for the perl-HTML-Form package.
Group: Default

%description license
license components for the perl-HTML-Form package.


%package perl
Summary: perl components for the perl-HTML-Form package.
Group: Default
Requires: perl-HTML-Form = %{version}-%{release}

%description perl
perl components for the perl-HTML-Form package.


%prep
%setup -q -n HTML-Form-6.10
cd %{_builddir}/HTML-Form-6.10

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-HTML-Form
cp %{_builddir}/HTML-Form-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/perl-HTML-Form/1901d391230618a9285903a4c6442ebf9affa678
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/HTML::Form.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-HTML-Form/1901d391230618a9285903a4c6442ebf9affa678

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
